export { errorRule } from "@/core/sampling/rules/error"
export { createLatencyRule } from "@/core/sampling/rules/latency"
export { createRandomRule } from "@/core/sampling/rules/random"
export { createConsistentRule } from "@/core/sampling/rules/consistent"
export type { LatencyConfig } from "@/core/sampling/rules/latency"
export type { ConsistentConfig } from "@/core/sampling/rules/consistent"
